# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 0  # disable version updates, only allow security updates
    schedule:
      interval: "weekly"
    groups:  # group updates
      maven-packages:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 0  # disable version updates, only allow security updates
    schedule:
      interval: "weekly"
    groups: # group updates
      npm-packages:
        patterns:
          - "*"
