/**
 * TaskBoard
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';

export interface TaskDto { 
    id?: string;
    createdAt?: Date;
    updatedAt?: Date;
    title: string;
    description: string;
    status?: TaskDto.StatusEnum;
    assignee?: UserDto;
}
export namespace TaskDto {
    export type StatusEnum = 'TODO' | 'DOING' | 'DONE';
    export const StatusEnum = {
        TODO: 'TODO' as StatusEnum,
        DOING: 'DOING' as StatusEnum,
        DONE: 'DONE' as StatusEnum
    };
}